In [3]:
import polars as pl
from pathlib import Path

In [24]:
paths = [
    p for p in Path("metadata").glob("*.parquet")
    if p.stat().st_size > 0
]
df = pl.scan_parquet(paths).collect()

In [26]:
len(df)

105994131

In [27]:
df.write_parquet("cellar_metadata.parquet")

In [5]:
df = pl.read_parquet("cellar_metadata.parquet")

In [ ]:
df = df.unique() #remove duplicates

In [9]:
df.write_parquet("cellar_metadata.parquet")

In [8]:
len(df)

33784893

In [ ]:
df["type"].unique().to_list()

In [4]:
df.head(100)

shape: (100, 4)
┌─────────────────────────────────┬──────────┬───────┬────────────┐
│ item                            ┆ langCode ┆ type  ┆ date       │
│ ---                             ┆ ---      ┆ ---   ┆ ---        │
│ str                             ┆ str      ┆ str   ┆ str        │
╞═════════════════════════════════╪══════════╪═══════╪════════════╡
│ http://publications.europa.eu/… ┆ BUL      ┆ pdf   ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ BUL      ┆ pdf   ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ BUL      ┆ pdf   ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ BUL      ┆ xhtml ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ BUL      ┆ xhtml ┆ 2009-02-10 │
│ …                               ┆ …        ┆ …     ┆ …          │
│ http://publications.europa.eu/… ┆ SPA      ┆ fmx4  ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ EST      ┆ pdf   ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ EST      ┆ pdf   ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ EST      ┆ pdf   ┆ 2009-02-10 │
│ http://publications.europa.eu/… ┆ EST      ┆ xhtml ┆ 2009-02-10 │
└─────────────────────────────────┴──────────┴───────┴────────────┘

In [6]:
df["langCode"].unique()

shape: (89,)
Series: 'langCode' [str]
[
	"PUS"
	"CKB"
	"FRA"
	"SRP"
	"MYA"
	…
	"NLD"
	"THA"
	"LAT"
	"MOL"
	"KHM"
]

In [7]:
df.filter(pl.col("langCode") == "NOR")

shape: (1_794, 4)
┌─────────────────────────────────┬──────────┬────────┬────────────┐
│ item                            ┆ langCode ┆ type   ┆ date       │
│ ---                             ┆ ---      ┆ ---    ┆ ---        │
│ str                             ┆ str      ┆ str    ┆ str        │
╞═════════════════════════════════╪══════════╪════════╪════════════╡
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2022-09-30 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2022-09-30 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2022-09-30 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2022-09-30 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdfa2a ┆ 2022-09-30 │
│ …                               ┆ …        ┆ …      ┆ …          │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2023-06-19 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2023-06-19 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdf    ┆ 2023-06-19 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdfx4  ┆ 2023-06-19 │
│ http://publications.europa.eu/… ┆ NOR      ┆ pdfx4  ┆ 2023-06-19 │
└─────────────────────────────────┴──────────┴────────┴────────────┘